### ISSUE TITLE
问答模块无法正常使用

### ISSUE THREAD

**Issue by scalaKing** [blmoistawinde/HarvestText#46]
你好，我尝试使用您的问答模块跑demo，就是运行naiveKGQA.py这个Python脚本，结果直接报如下错误：
Traceback (most recent call last):
  File "D:\workspace\git\HarvestText\examples\naiveKGQA.py", line 165, in <module>
    print("答："+QA.answer(question0))
  File "D:\workspace\git\HarvestText\examples\naiveKGQA.py", line 110, in answer
    answers = self.search_answers(search0)
  File "D:\workspace\git\HarvestText\examples\naiveKGQA.py", line 99, in search_answers
    records = self.KG.query(search0)
  File "D:\ProgramData\anaconda3\envs\kg_env\lib\site-packages\rdflib\graph.py", line 1127, in query
    result = plugin.get(result, query.Result)
  File "D:\ProgramData\anaconda3\envs\kg_env\lib\site-packages\rdflib\plugin.py", line 107, in get
    return p.getClass()
  File "D:\ProgramData\anaconda3\envs\kg_env\lib\site-packages\rdflib\plugin.py", line 69, in getClass
    module = __import__(self.module_path, globals(), locals(), [""])
  File "D:\ProgramData\anaconda3\envs\kg_env\lib\site-packages\rdflib\plugins\sparql\__init__.py", line 33, in <module>
    from . import parser
  File "D:\ProgramData\anaconda3\envs\kg_env\lib\site-packages\rdflib\plugins\sparql\parser.py", line 184, in <module>
    Param('prefix', PN_PREFIX)) + Suppress(':').leaveWhitespace()
  File "D:\ProgramData\anaconda3\envs\kg_env\lib\site-packages\rdflib\plugins\sparql\parserutils.py", line 114, in __init__
    self.name = name
AttributeError: can't set attribute

操作系统：Win10 专业版

python版本：3.6.13

HarvestText版本：0.8.1.8

**Comment by stellarissss** [comment]
问题好像在rdflib和pyparsing库的版本冲突上:

rdflib的parserutils.py在初始化时会用self.name = name来赋值
但pyparsing 3.x开始, 把name改成了只读
于是乎旧版rdflib报错, AttributeError: can't set attribute

### 你可以

1. 降级 pyparsing
`pip install pyparsing==2.4.7`
pyparsing 2.x的name是普通可读写属性, 跟旧版rdflib和谐共处, 你当前的Python3.6环境直接就能用

2. 升级 Python 和 rdflib
如果你愿意把Python升到 3.7+, 也可以直接升级rdflib到 6.0 以上版本
`pip install rdflib>=6.0.0`

如果这是一个普遍问题, 也建议在你的requirements里固定一下版本
`rdflib==5.0.0
pyparsing==2.4.7`

问题应该出在这里, 但如果没有解决问题的话~~私密马赛~~
